{% set name = "orekit" %}
{% set version = "11.0" %}
{% set artifact_filename = "v11_0_0" %}
{% set sha256 = "aa1ed31ef6e440abc6ccfe90c83cb8a2eb0da1e4f995f5996ad9c79f5ac0465b" %}  

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ artifact_filename }}.zip
  url: https://github.com/petrushy/orekit_python_artifacts/archive/{{ artifact_filename }}.zip  # [not osx]

build:
  number: 0

  rpaths:
    - lib/
    - jre/lib/amd64/
    - jre/lib/amd64/server/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - openjdk 8

  host:
    - python
    - setuptools
    - jcc
    - openjdk 8

  run:
    - python
    - openjdk 8

test:
  imports:
    - orekit

  source_files:
    - test/*.py
    - test/orekit-data.zip
    - test/resources.zip
    - test/resources/ccsds/*.txt

about:
  home: https://www.orekit.org/forge/projects/orekit-python-wrapper
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'An accurate and efficient core layer for space flight dynamics applications '

  description:
    Orekit aims at providing accurate and efficient low level components for
    the development of flight dynamics applications. It is designed to be
    easily used in very different contexts, from quick studies up to critical operations.
    As a library, Orekit provides basic elements (orbits, dates, attitude, frames, ...) and
    various algorithms to handle them (conversions, propagations, pointing, ....).

    The Orekit library is written in java. This package provides a python wrapper to that library.

  doc_url: https://www.orekit.org/static/apidocs/

extra:
  recipe-maintainers:
    - petrushy
