{% set name = "orekit" %}
{% set version = "10.0" %}
{% set artifact_filename = "v10_0_4" %}
{% set sha256 = "d2ac8c4d8613e89821afb562e77d7c18518d0201e1b3d7e06839d98f873bb7ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ artifact_filename }}.zip
  url: https://github.com/petrushy/orekit_python_artifacts/archive/{{ artifact_filename }}.zip
  sha256: {{ sha256 }}

build:
  number: 6

  rpaths:
    - lib/
    - jre/lib/amd64/
    - jre/lib/amd64/server/

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - jcc >=3.6
    # Force anaconda openjdk 
    - openjdk 8.0.152

  run:
    - python
    # Force anaconda openjdk
    - openjdk 8.0.152

test:
  imports:
    - orekit

  source_files:
    - test/*.py
    - test/orekit-data.zip
    - test/resources.zip

about:
  home: https://www.orekit.org/forge/projects/orekit-python-wrapper
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: 'An accurate and efficient core layer for space flight dynamics applications'

  description:
    Orekit aims at providing accurate and efficient low level components for
    the development of flight dynamics applications. It is designed to be
    easily used in very different contexts, from quick studies up to critical operations.
    As a library, Orekit provides basic elements (orbits, dates, attitude, frames, ...) and
    various algorithms to handle them (conversions, propagations, pointing, ....).

    The Orekit library is written in java. This package provides a python wrapper to that library.

  doc_url: https://www.orekit.org/static/apidocs/

extra:
  recipe-maintainers:
    - petrushy
