appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: TS0uvtAcpykaHQoQGRVA6v8+wzQb8OjJJfnzP9JoPeOrvNVufqKf3Jq7g/W2pLse+22rg66K1+9xs5D7ROdnVZzS2nLVLlbhkWvBsMweZV25V2fnK9ks9/0faoVlCLQA8cCW8RafrMfTr6y/jujlhMprXgKcqMd1BNqCmLo+kFlRe+i8p9Zs7KjeImeiaAcN7cqwnntfxWswguSeVaRrV3O5DB7jIrElI/5jC9XMGW4x86dGY25zoTzTacPASe/jbRojI945cpunHxGg59XYqcEEpMr2xThSzlCSRQ5TbW5WL1Zjh9fJ+tyoXPR3u+ZRkc4bbmpMbsphGoavF7tVXSfg8OpHJZfWIgh64BaJFBJMeFSVQC6/cOHqdxGcuT78PRLuderKpb0q5FzRrIFdH4lygF3Wl/HlKZlZHaSISAHH1pg6OkYFxmnBCb7mPds0bgS+wsDN35nDbyrVaQlSIVCgk9WyPAMSGkLABJiMs4OLf29mkjAUyZToK0UoLyJa4mYe0W8axMyH+0M5XrdyMiQPXBdzUqCvt1Ggwdf/XxCozPUq/vZN7Ber/3e7ZCBkjDvuAcEbhmkTF3tU8c63MhYwQMxWOzTUz5qIZ1l2j0BjshapZJk92r+j9gpCGKeK+t2PCI4afDur+G4WAdJxzqoyhca0/UWOiwQ5GGU57eo=}
